### ISSUE TITLE
Question: Best way to share code between aliases?

### ISSUE THREAD

**Issue by desbma** [KnorrFG/dotree#3]
Hi,

I think this project idea is brillant, I have many aliases with short names and I sometimes have to look at the shell code to remember the exact letters.

However I have a question, I usually organize aliases/functions with same target domain in dedicated files, and that allows sharing code. For example I have many aliases calling [yt-dlp](https://github.com/yt-dlp/yt-dlp), to download video, stream audio, stream video, search and choose with a fzf menu which video to play, etc. Currently these aliases call private subfunctions, or use variables declared in the same file. This does not seem to be possible with dotree, unless I source a common shell file first for each command declaration, which is not ideal because it duplicates code between 2 different places.

Is there a better way to share code between aliases ?

Thanks

**Comment by KnorrFG** [comment]
Hey, currently, the only option is to source a shell script. But I have an idea for a feature that addresses this. 
I'm thinking of a `header` directive at the toplevel, that you can then include in a command

```
header yt_helpers !"
VAR_1=foo
some_func() {...}
"!

menu root {
    d: cmd {
          headers yt_helpers
          "...;some_func;..."
    }
}
```
This would then prepend the headers content to the shell string. It would be possible to define multiple headers, and also to include multiple headers. This is effectively the same as sourcing in bash, but you have everything in one file

Would that work for you?

I can't promise you to get to that on the weekend, but I'll try.

**Comment by desbma** [comment]
Yeah I think that would address my issue, thanks.

Minor nitpick on the naming though: maybe `include` is more descriptive than `headers`? But it's entirely subjective and up to you of course.

**Comment by KnorrFG** [comment]
0.6.0 implements the snippet feature. Take a look at the readme please :)
<https://github.com/KnorrFG/dotree#snippets>
