### ISSUE TITLE
How to have arbitrary number of arguments to a command?

### ISSUE THREAD

**Issue by desbma** [KnorrFG/dotree#4]
Stupid example to illustrate:
```
menu root {
    w: cmd {
        vars urls
        "Download URLs" - "wget ${urls}"
    }
}
```

Now I can download a single URL with `dotree w FIRST_URL`, more than one by quoting as a single argument `dotree w 'FIRST_URL SECOND_URL'`, but that does not work with the interactive prompt.

**Comment by KnorrFG** [comment]
Using your example, when I type `github.com reddit.com` into the interactive prompt, I end up with `index.html` (which is githubs index) and `index.html.1`, which is reddits index, in the current working directory. I'd say that works as expected

**Comment by desbma** [comment]
OK, never mind.

**Comment by KnorrFG** [comment]
If it doesn't work for you like this, then this is indeed an issue. But since it works for me, we would need to find out what is happening on your pc, and how I can reproduce it.

**Comment by desbma** [comment]
By "never mind", I meant "you are right, it works, I opened this issue too fast" :wink:

**Comment by theAkito** [comment]
Is this also supposed to work in a sub-menu, i.e. non-root menu?

Cannot get it to work, because it always passes the arguments as a single literal string.

**Comment by KnorrFG** [comment]
Hey, the root menu is treated like every other menu. So the behavior is the same. It should work. But that depends on your interpreter and how it handles variables. For example, in bash:

``` bash
foo(){
  echo 1: $1
  echo 2: $2
}

# calls foo with $1 = 1 and $2 = 2
foo 1 2

x="4 5"

# calls foo with $1 = 4 and $2 = 5
foo $x

# calls foo with $1 = "4 5" and without $2
foo "$x"

```
So if this works or not depends on your shell, and how you use the env vars within it.

**Comment by theAkito** [comment]
> depends on your shell

Okay, indeed, works in Bash. Thanks!
