### ISSUE TITLE
Feature Request/Discussion: More verbose output option(s)

### ISSUE THREAD

**Issue by citrusmunch** [KnorrFG/dotree#6]
Currently the output from a successful `dt` invocation is nothing besides whatever is being called. However, I've been finding that I'll run a command with some side effects and then looking back on my shell history/ouput I can't see what's been run already. Re-running a command (non-consecutively) is also not really possible.

A workaround is to run e.g. `dt xyz some_arg` at the cost of needing to provide everything up front (non-interactive).

At the simplest, I think it would be nice to be able to echo the final invocation after an interactive session:

```ShellSession
$ dt
dt xyz some_arg

output of doing z ...
```

That should usually provide enough context and could also be copy-pasted. Additionally, a quiet/verbosity flag might also be useful in case people are piping output, for instance.

Getting *fancier*:

+ the echo could be previewed as one traverses the tree while typing
+ printing the final `"name" - "bash command"` leaf that's run
+ a full-blown `@` show/hide token in the config à la `just`; and maybe toggling that interactively too?
+ modifying shell history so re-running is more seamless than copy-pasting from scrollback

I don't mean to introduce bloat (I'd likely turn to an emacs hydra if I needed all that), but I thought I'd include it since it's related and I had some fun brainstorming. The simplest solution alone would make a world of difference!

I haven't touched rust in years, but maybe I'll make an excuse to pick it up again and toy around with some of this. Just wanted to put this all out there for discussion!

**Comment by KnorrFG** [comment]
I like your ideas. However, modifying the shell history is only half the work. The shell also has to reload the history. But yeah, also doable. But that would then also load all commands that were executed in other shells in the mean time, and that would annoy me. But it could be made a config option.

Alternatively, maybe a -p flag to rerun the last command?

I think currently, the dotree code is basically undocumented. I should change that, to make contributions easier. If you want to try this your self, and have any questions, please ask.

**Comment by KnorrFG** [comment]
The default behavior now is to echo a command, this can be switched with `echo off` at the top of the file. A single command's behavior can be toggled with the `@` operator. However, I cannot substitute the variables in the command, because the command is actually executed with those variables, and the values are passed via environment vars. Since any text interpreter is supported as shell, to substitute variables in the command string, I'd need to check the shell and then do the substitution based on that. And that is not feasible.
