### ISSUE TITLE
Configuration Syntax

### ISSUE THREAD

**Issue by theAkito** [KnorrFG/dotree#9]
First of all, thank you for this great tool!

This is more of a discussion, which, depending on its outcome, may lead to a specific suggestion.

Is the configuration syntax based on some agreed upon standard or is it just hand-crafted for this product?

When I saw it the first time, it reminded me of a JSON extension, like [Jsonnet](https://jsonnet.org/), for example.

Is there a specific reason to use this syntax, besides "simplicity"?

If both questions are answered with "no", I would suggest using something like [Jsonnet](https://jsonnet.org/) for the following reasons.

* An uncommon extension of JSON is still a million times more common/accessible/usable, than a unique syntax specifically designed for a single product, which you never see anywhere else.
* There are [plenty of Jsonnet language helpers with syntax highlighting](https://jsonnet.org/learning/tools.html) etc. for editors like e.g. Visual Studio Code or VSCodium.
* You can leverage all tools Jsonnet already offers by default, like variables, etc., snippet & configuration generation, like e.g. `ini` files. That means, you wouldn't need to build this from scratch. It's just there.
* Yes, there are maintained Rust libraries already available. [This is the recommended one](https://github.com/CertainLach/jrsonnet).

From my point of view, switching to Jsonnet would be only an improvement, without worsening the current experience. I guess, the only "increase in complexity" I see, is the addition of a comma after each menu & wrapping all menus inside two absolute braces. Otherwise, everything stays exactly the same, complexity-wise. It would *change*, but it would not increase complexity.

**Comment by KnorrFG** [comment]
Hey, thanks for your initiative, I appreciate every form of constructive feedback. 

The syntax is handcrafted, and I think I'll keep it this way. For once, the work is already done, and extending it easy, and I have all the freedom in the world. The `@` operator would probably not be possible in jsonnet. Also, it will give me a reason to learn how to write a tree sitter grammar at some point :D

**Comment by theAkito** [comment]
I see. Thanks for the consideration!
